// Bus Route Display � DE1-SoC  (AUTO-GENERATED by gen_rom.py)
// Phase 3: 3 buses, demo mode (SW[9]), road topology animation.
//
// SW[1:0]=scenario  SW[4:2]=time slot  SW[9]=demo mode
// Stop colours: Blue=Bus0/1-route  Green=Bus1-route  DimWhite=inactive
// Bus dots:     White=Bus0(ML)  Yellow=Bus1(ML)  Cyan=Bus2(all-stops)
// Demo mode:    SW[9]=1 cycles all 8 time slots per scenario then advances scenario

module bus_route (
    input  wire        CLOCK_50,
    input  wire [3:0]  KEY,
    input  wire [9:0]  SW,
    output wire [9:0]  LEDR,
    output wire [6:0]  HEX0, HEX1, HEX2, HEX3, HEX4, HEX5,
    output wire        GPIO_0_0
);

    localparam NUM_LEDS   = 156;
    localparam T0H=18, T0L=45, T1H=45, T1L=18, TRESET=3000;
    localparam MOVE_SPD   = 20;   // frames per LED step (~96ms)
    localparam DWELL_TIME = 400;  // frames at stop (~1.9s)
    assign HEX0=7'h7F; assign HEX1=7'h7F; assign HEX2=7'h7F;
    assign HEX3=7'h7F; assign HEX4=7'h7F; assign HEX5=7'h7F;

    reg [1:0] rst_sync;
    wire rst_n = rst_sync[1];
    always @(posedge CLOCK_50) rst_sync <= {rst_sync[0], KEY[0]};

    // Demo mode: SW[9]=1 cycles all 8 time slots for one scenario, then
    // advances to the next scenario, cycling all 4 scenarios before looping.
    // 1,500,000,000 / 50MHz = exactly 30 seconds per time slot.
    reg [30:0] demo_ctr;
    reg [2:0]  demo_ts;
    reg [1:0]  demo_sc;
    always @(posedge CLOCK_50 or negedge rst_n) begin
        if (!rst_n) begin demo_ctr <= 31'd0; demo_ts <= 3'd0; demo_sc <= 2'd0; end
        else begin
            if (demo_ctr == 31'd1_499_999_999) begin
                demo_ctr <= 31'd0;
                if (demo_ts == 3'd7) begin
                    demo_ts <= 3'd0;
                    demo_sc <= demo_sc + 2'd1;  // wraps 3->0 naturally
                end else begin
                    demo_ts <= demo_ts + 3'd1;
                end
            end else begin
                demo_ctr <= demo_ctr + 31'd1;
            end
        end
    end
    wire [1:0] eff_sc   = SW[9] ? demo_sc : SW[1:0];
    wire [2:0] eff_ts   = SW[9] ? demo_ts : SW[4:2];
    wire [4:0] rom_addr = {eff_sc, eff_ts};

    reg  [4:0] sw_prev;
    always @(posedge CLOCK_50 or negedge rst_n) begin
        if (!rst_n) sw_prev <= 5'h1F;
        else if (frame_done) sw_prev <= rom_addr;
    end
    wire sw_changed = (rom_addr != sw_prev);

    // route_stop_led(addr, bus, idx) -> LED number
    function [7:0] route_stop_led;
        input [4:0] addr;
        input       bus;
        input [3:0] idx;
        begin
            case ({addr, bus, idx})
                10'h000: route_stop_led = 8'd106;
                10'h001: route_stop_led = 8'd33;
                10'h002: route_stop_led = 8'd65;
                10'h003: route_stop_led = 8'd58;
                10'h004: route_stop_led = 8'd95;
                10'h005: route_stop_led = 8'd44;
                10'h006: route_stop_led = 8'd50;
                10'h007: route_stop_led = 8'd70;
                10'h008: route_stop_led = 8'd114;
                10'h010: route_stop_led = 8'd142;
                10'h011: route_stop_led = 8'd11;
                10'h012: route_stop_led = 8'd1;
                10'h013: route_stop_led = 8'd78;
                10'h014: route_stop_led = 8'd25;
                10'h015: route_stop_led = 8'd21;
                10'h020: route_stop_led = 8'd106;
                10'h021: route_stop_led = 8'd33;
                10'h022: route_stop_led = 8'd65;
                10'h023: route_stop_led = 8'd58;
                10'h024: route_stop_led = 8'd95;
                10'h025: route_stop_led = 8'd44;
                10'h026: route_stop_led = 8'd50;
                10'h027: route_stop_led = 8'd70;
                10'h028: route_stop_led = 8'd114;
                10'h030: route_stop_led = 8'd142;
                10'h031: route_stop_led = 8'd11;
                10'h032: route_stop_led = 8'd1;
                10'h033: route_stop_led = 8'd78;
                10'h034: route_stop_led = 8'd25;
                10'h035: route_stop_led = 8'd21;
                10'h040: route_stop_led = 8'd106;
                10'h041: route_stop_led = 8'd33;
                10'h042: route_stop_led = 8'd65;
                10'h043: route_stop_led = 8'd58;
                10'h044: route_stop_led = 8'd95;
                10'h045: route_stop_led = 8'd44;
                10'h046: route_stop_led = 8'd50;
                10'h047: route_stop_led = 8'd70;
                10'h048: route_stop_led = 8'd78;
                10'h050: route_stop_led = 8'd142;
                10'h051: route_stop_led = 8'd11;
                10'h052: route_stop_led = 8'd1;
                10'h053: route_stop_led = 8'd114;
                10'h054: route_stop_led = 8'd25;
                10'h055: route_stop_led = 8'd21;
                10'h060: route_stop_led = 8'd106;
                10'h061: route_stop_led = 8'd33;
                10'h062: route_stop_led = 8'd65;
                10'h063: route_stop_led = 8'd58;
                10'h064: route_stop_led = 8'd95;
                10'h065: route_stop_led = 8'd44;
                10'h066: route_stop_led = 8'd50;
                10'h067: route_stop_led = 8'd70;
                10'h068: route_stop_led = 8'd78;
                10'h070: route_stop_led = 8'd142;
                10'h071: route_stop_led = 8'd11;
                10'h072: route_stop_led = 8'd1;
                10'h073: route_stop_led = 8'd114;
                10'h074: route_stop_led = 8'd25;
                10'h075: route_stop_led = 8'd21;
                10'h080: route_stop_led = 8'd106;
                10'h081: route_stop_led = 8'd33;
                10'h082: route_stop_led = 8'd65;
                10'h083: route_stop_led = 8'd58;
                10'h084: route_stop_led = 8'd95;
                10'h085: route_stop_led = 8'd44;
                10'h086: route_stop_led = 8'd50;
                10'h087: route_stop_led = 8'd70;
                10'h088: route_stop_led = 8'd78;
                10'h090: route_stop_led = 8'd142;
                10'h091: route_stop_led = 8'd11;
                10'h092: route_stop_led = 8'd1;
                10'h093: route_stop_led = 8'd114;
                10'h094: route_stop_led = 8'd25;
                10'h095: route_stop_led = 8'd21;
                10'h0A0: route_stop_led = 8'd106;
                10'h0A1: route_stop_led = 8'd33;
                10'h0A2: route_stop_led = 8'd65;
                10'h0A3: route_stop_led = 8'd58;
                10'h0A4: route_stop_led = 8'd95;
                10'h0A5: route_stop_led = 8'd44;
                10'h0A6: route_stop_led = 8'd50;
                10'h0A7: route_stop_led = 8'd70;
                10'h0A8: route_stop_led = 8'd114;
                10'h0B0: route_stop_led = 8'd142;
                10'h0B1: route_stop_led = 8'd11;
                10'h0B2: route_stop_led = 8'd1;
                10'h0B3: route_stop_led = 8'd78;
                10'h0B4: route_stop_led = 8'd25;
                10'h0B5: route_stop_led = 8'd21;
                10'h0C0: route_stop_led = 8'd106;
                10'h0C1: route_stop_led = 8'd33;
                10'h0C2: route_stop_led = 8'd65;
                10'h0C3: route_stop_led = 8'd58;
                10'h0C4: route_stop_led = 8'd95;
                10'h0C5: route_stop_led = 8'd44;
                10'h0C6: route_stop_led = 8'd50;
                10'h0C7: route_stop_led = 8'd70;
                10'h0C8: route_stop_led = 8'd78;
                10'h0D0: route_stop_led = 8'd142;
                10'h0D1: route_stop_led = 8'd11;
                10'h0D2: route_stop_led = 8'd1;
                10'h0D3: route_stop_led = 8'd114;
                10'h0D4: route_stop_led = 8'd25;
                10'h0D5: route_stop_led = 8'd21;
                10'h0E0: route_stop_led = 8'd106;
                10'h0E1: route_stop_led = 8'd33;
                10'h0E2: route_stop_led = 8'd65;
                10'h0E3: route_stop_led = 8'd58;
                10'h0E4: route_stop_led = 8'd95;
                10'h0E5: route_stop_led = 8'd44;
                10'h0E6: route_stop_led = 8'd50;
                10'h0E7: route_stop_led = 8'd70;
                10'h0E8: route_stop_led = 8'd114;
                10'h0F0: route_stop_led = 8'd142;
                10'h100: route_stop_led = 8'd106;
                10'h101: route_stop_led = 8'd33;
                10'h102: route_stop_led = 8'd65;
                10'h103: route_stop_led = 8'd58;
                10'h104: route_stop_led = 8'd95;
                10'h105: route_stop_led = 8'd44;
                10'h106: route_stop_led = 8'd50;
                10'h107: route_stop_led = 8'd70;
                10'h108: route_stop_led = 8'd78;
                10'h110: route_stop_led = 8'd142;
                10'h111: route_stop_led = 8'd11;
                10'h112: route_stop_led = 8'd1;
                10'h113: route_stop_led = 8'd114;
                10'h114: route_stop_led = 8'd25;
                10'h115: route_stop_led = 8'd21;
                10'h120: route_stop_led = 8'd106;
                10'h121: route_stop_led = 8'd33;
                10'h122: route_stop_led = 8'd65;
                10'h123: route_stop_led = 8'd58;
                10'h124: route_stop_led = 8'd95;
                10'h125: route_stop_led = 8'd44;
                10'h126: route_stop_led = 8'd50;
                10'h127: route_stop_led = 8'd70;
                10'h128: route_stop_led = 8'd78;
                10'h130: route_stop_led = 8'd142;
                10'h131: route_stop_led = 8'd11;
                10'h132: route_stop_led = 8'd1;
                10'h133: route_stop_led = 8'd21;
                10'h134: route_stop_led = 8'd25;
                10'h135: route_stop_led = 8'd114;
                10'h140: route_stop_led = 8'd106;
                10'h141: route_stop_led = 8'd33;
                10'h142: route_stop_led = 8'd65;
                10'h143: route_stop_led = 8'd58;
                10'h144: route_stop_led = 8'd95;
                10'h145: route_stop_led = 8'd44;
                10'h146: route_stop_led = 8'd50;
                10'h147: route_stop_led = 8'd70;
                10'h148: route_stop_led = 8'd114;
                10'h150: route_stop_led = 8'd142;
                10'h151: route_stop_led = 8'd11;
                10'h152: route_stop_led = 8'd1;
                10'h153: route_stop_led = 8'd78;
                10'h154: route_stop_led = 8'd25;
                10'h155: route_stop_led = 8'd21;
                10'h160: route_stop_led = 8'd106;
                10'h161: route_stop_led = 8'd33;
                10'h162: route_stop_led = 8'd65;
                10'h163: route_stop_led = 8'd58;
                10'h164: route_stop_led = 8'd95;
                10'h165: route_stop_led = 8'd44;
                10'h166: route_stop_led = 8'd50;
                10'h167: route_stop_led = 8'd70;
                10'h168: route_stop_led = 8'd114;
                10'h170: route_stop_led = 8'd142;
                10'h171: route_stop_led = 8'd11;
                10'h172: route_stop_led = 8'd1;
                10'h173: route_stop_led = 8'd78;
                10'h174: route_stop_led = 8'd25;
                10'h175: route_stop_led = 8'd21;
                10'h180: route_stop_led = 8'd106;
                10'h181: route_stop_led = 8'd33;
                10'h182: route_stop_led = 8'd65;
                10'h183: route_stop_led = 8'd58;
                10'h184: route_stop_led = 8'd95;
                10'h185: route_stop_led = 8'd44;
                10'h186: route_stop_led = 8'd50;
                10'h187: route_stop_led = 8'd70;
                10'h188: route_stop_led = 8'd114;
                10'h190: route_stop_led = 8'd142;
                10'h191: route_stop_led = 8'd11;
                10'h192: route_stop_led = 8'd1;
                10'h193: route_stop_led = 8'd78;
                10'h194: route_stop_led = 8'd25;
                10'h195: route_stop_led = 8'd21;
                10'h1A0: route_stop_led = 8'd106;
                10'h1A1: route_stop_led = 8'd33;
                10'h1A2: route_stop_led = 8'd65;
                10'h1A3: route_stop_led = 8'd58;
                10'h1A4: route_stop_led = 8'd95;
                10'h1A5: route_stop_led = 8'd44;
                10'h1A6: route_stop_led = 8'd50;
                10'h1A7: route_stop_led = 8'd70;
                10'h1A8: route_stop_led = 8'd114;
                10'h1B0: route_stop_led = 8'd142;
                10'h1B1: route_stop_led = 8'd11;
                10'h1B2: route_stop_led = 8'd1;
                10'h1B3: route_stop_led = 8'd78;
                10'h1B4: route_stop_led = 8'd25;
                10'h1B5: route_stop_led = 8'd21;
                10'h1C0: route_stop_led = 8'd106;
                10'h1C1: route_stop_led = 8'd33;
                10'h1C2: route_stop_led = 8'd65;
                10'h1C3: route_stop_led = 8'd58;
                10'h1C4: route_stop_led = 8'd95;
                10'h1C5: route_stop_led = 8'd44;
                10'h1C6: route_stop_led = 8'd50;
                10'h1C7: route_stop_led = 8'd70;
                10'h1C8: route_stop_led = 8'd78;
                10'h1D0: route_stop_led = 8'd142;
                10'h1D1: route_stop_led = 8'd11;
                10'h1D2: route_stop_led = 8'd1;
                10'h1D3: route_stop_led = 8'd114;
                10'h1D4: route_stop_led = 8'd25;
                10'h1D5: route_stop_led = 8'd21;
                10'h1E0: route_stop_led = 8'd106;
                10'h1E1: route_stop_led = 8'd33;
                10'h1E2: route_stop_led = 8'd65;
                10'h1E3: route_stop_led = 8'd58;
                10'h1E4: route_stop_led = 8'd95;
                10'h1E5: route_stop_led = 8'd44;
                10'h1E6: route_stop_led = 8'd50;
                10'h1E7: route_stop_led = 8'd70;
                10'h1E8: route_stop_led = 8'd114;
                10'h1F0: route_stop_led = 8'd142;
                10'h1F1: route_stop_led = 8'd1;
                10'h1F2: route_stop_led = 8'd78;
                10'h1F3: route_stop_led = 8'd25;
                10'h200: route_stop_led = 8'd106;
                10'h201: route_stop_led = 8'd33;
                10'h202: route_stop_led = 8'd65;
                10'h203: route_stop_led = 8'd58;
                10'h204: route_stop_led = 8'd95;
                10'h205: route_stop_led = 8'd44;
                10'h206: route_stop_led = 8'd50;
                10'h207: route_stop_led = 8'd70;
                10'h208: route_stop_led = 8'd78;
                10'h210: route_stop_led = 8'd142;
                10'h211: route_stop_led = 8'd1;
                10'h212: route_stop_led = 8'd21;
                10'h213: route_stop_led = 8'd114;
                10'h220: route_stop_led = 8'd65;
                10'h221: route_stop_led = 8'd33;
                10'h222: route_stop_led = 8'd106;
                10'h223: route_stop_led = 8'd70;
                10'h224: route_stop_led = 8'd95;
                10'h225: route_stop_led = 8'd58;
                10'h226: route_stop_led = 8'd44;
                10'h227: route_stop_led = 8'd50;
                10'h228: route_stop_led = 8'd142;
                10'h229: route_stop_led = 8'd11;
                10'h22A: route_stop_led = 8'd1;
                10'h230: route_stop_led = 8'd114;
                10'h231: route_stop_led = 8'd25;
                10'h232: route_stop_led = 8'd21;
                10'h233: route_stop_led = 8'd78;
                10'h240: route_stop_led = 8'd106;
                10'h241: route_stop_led = 8'd33;
                10'h242: route_stop_led = 8'd65;
                10'h243: route_stop_led = 8'd95;
                10'h244: route_stop_led = 8'd58;
                10'h245: route_stop_led = 8'd44;
                10'h246: route_stop_led = 8'd50;
                10'h247: route_stop_led = 8'd70;
                10'h248: route_stop_led = 8'd114;
                10'h250: route_stop_led = 8'd142;
                10'h251: route_stop_led = 8'd11;
                10'h252: route_stop_led = 8'd1;
                10'h253: route_stop_led = 8'd21;
                10'h254: route_stop_led = 8'd25;
                10'h255: route_stop_led = 8'd78;
                10'h260: route_stop_led = 8'd106;
                10'h261: route_stop_led = 8'd33;
                10'h262: route_stop_led = 8'd65;
                10'h263: route_stop_led = 8'd95;
                10'h264: route_stop_led = 8'd58;
                10'h265: route_stop_led = 8'd44;
                10'h266: route_stop_led = 8'd50;
                10'h267: route_stop_led = 8'd70;
                10'h268: route_stop_led = 8'd114;
                10'h270: route_stop_led = 8'd142;
                10'h271: route_stop_led = 8'd25;
                10'h272: route_stop_led = 8'd21;
                10'h273: route_stop_led = 8'd78;
                10'h280: route_stop_led = 8'd106;
                10'h281: route_stop_led = 8'd33;
                10'h282: route_stop_led = 8'd65;
                10'h283: route_stop_led = 8'd95;
                10'h284: route_stop_led = 8'd58;
                10'h285: route_stop_led = 8'd44;
                10'h286: route_stop_led = 8'd50;
                10'h287: route_stop_led = 8'd70;
                10'h288: route_stop_led = 8'd114;
                10'h290: route_stop_led = 8'd142;
                10'h291: route_stop_led = 8'd11;
                10'h292: route_stop_led = 8'd1;
                10'h293: route_stop_led = 8'd78;
                10'h294: route_stop_led = 8'd25;
                10'h295: route_stop_led = 8'd21;
                10'h2A0: route_stop_led = 8'd106;
                10'h2A1: route_stop_led = 8'd33;
                10'h2A2: route_stop_led = 8'd65;
                10'h2A3: route_stop_led = 8'd95;
                10'h2A4: route_stop_led = 8'd58;
                10'h2A5: route_stop_led = 8'd44;
                10'h2A6: route_stop_led = 8'd50;
                10'h2A7: route_stop_led = 8'd70;
                10'h2A8: route_stop_led = 8'd114;
                10'h2B0: route_stop_led = 8'd142;
                10'h2B1: route_stop_led = 8'd1;
                10'h2B2: route_stop_led = 8'd78;
                10'h2B3: route_stop_led = 8'd25;
                10'h2B4: route_stop_led = 8'd21;
                10'h2C0: route_stop_led = 8'd106;
                10'h2C1: route_stop_led = 8'd33;
                10'h2C2: route_stop_led = 8'd65;
                10'h2C3: route_stop_led = 8'd58;
                10'h2C4: route_stop_led = 8'd95;
                10'h2C5: route_stop_led = 8'd44;
                10'h2C6: route_stop_led = 8'd50;
                10'h2C7: route_stop_led = 8'd70;
                10'h2C8: route_stop_led = 8'd78;
                10'h2D0: route_stop_led = 8'd114;
                10'h2D1: route_stop_led = 8'd142;
                10'h2D2: route_stop_led = 8'd1;
                10'h2D3: route_stop_led = 8'd25;
                10'h2E0: route_stop_led = 8'd106;
                10'h2E1: route_stop_led = 8'd33;
                10'h2E2: route_stop_led = 8'd65;
                10'h2E3: route_stop_led = 8'd95;
                10'h2E4: route_stop_led = 8'd58;
                10'h2E5: route_stop_led = 8'd44;
                10'h2E6: route_stop_led = 8'd50;
                10'h2E7: route_stop_led = 8'd70;
                10'h2E8: route_stop_led = 8'd78;
                10'h2F0: route_stop_led = 8'd142;
                10'h300: route_stop_led = 8'd106;
                10'h301: route_stop_led = 8'd33;
                10'h302: route_stop_led = 8'd65;
                10'h303: route_stop_led = 8'd58;
                10'h304: route_stop_led = 8'd95;
                10'h305: route_stop_led = 8'd44;
                10'h306: route_stop_led = 8'd50;
                10'h307: route_stop_led = 8'd70;
                10'h308: route_stop_led = 8'd114;
                10'h310: route_stop_led = 8'd142;
                10'h311: route_stop_led = 8'd11;
                10'h312: route_stop_led = 8'd1;
                10'h313: route_stop_led = 8'd21;
                10'h314: route_stop_led = 8'd25;
                10'h315: route_stop_led = 8'd78;
                10'h320: route_stop_led = 8'd106;
                10'h321: route_stop_led = 8'd33;
                10'h322: route_stop_led = 8'd65;
                10'h323: route_stop_led = 8'd58;
                10'h324: route_stop_led = 8'd95;
                10'h325: route_stop_led = 8'd44;
                10'h326: route_stop_led = 8'd50;
                10'h327: route_stop_led = 8'd70;
                10'h328: route_stop_led = 8'd78;
                10'h330: route_stop_led = 8'd142;
                10'h331: route_stop_led = 8'd11;
                10'h332: route_stop_led = 8'd1;
                10'h333: route_stop_led = 8'd21;
                10'h334: route_stop_led = 8'd25;
                10'h335: route_stop_led = 8'd114;
                10'h340: route_stop_led = 8'd106;
                10'h341: route_stop_led = 8'd33;
                10'h342: route_stop_led = 8'd65;
                10'h343: route_stop_led = 8'd58;
                10'h344: route_stop_led = 8'd95;
                10'h345: route_stop_led = 8'd44;
                10'h346: route_stop_led = 8'd50;
                10'h347: route_stop_led = 8'd70;
                10'h348: route_stop_led = 8'd78;
                10'h350: route_stop_led = 8'd142;
                10'h351: route_stop_led = 8'd11;
                10'h352: route_stop_led = 8'd1;
                10'h353: route_stop_led = 8'd21;
                10'h354: route_stop_led = 8'd25;
                10'h355: route_stop_led = 8'd114;
                10'h360: route_stop_led = 8'd106;
                10'h361: route_stop_led = 8'd33;
                10'h362: route_stop_led = 8'd65;
                10'h363: route_stop_led = 8'd58;
                10'h364: route_stop_led = 8'd95;
                10'h365: route_stop_led = 8'd44;
                10'h366: route_stop_led = 8'd50;
                10'h367: route_stop_led = 8'd70;
                10'h368: route_stop_led = 8'd114;
                10'h370: route_stop_led = 8'd142;
                10'h371: route_stop_led = 8'd11;
                10'h372: route_stop_led = 8'd1;
                10'h373: route_stop_led = 8'd78;
                10'h374: route_stop_led = 8'd21;
                10'h375: route_stop_led = 8'd25;
                10'h380: route_stop_led = 8'd106;
                10'h381: route_stop_led = 8'd33;
                10'h382: route_stop_led = 8'd65;
                10'h383: route_stop_led = 8'd58;
                10'h384: route_stop_led = 8'd95;
                10'h385: route_stop_led = 8'd44;
                10'h386: route_stop_led = 8'd50;
                10'h387: route_stop_led = 8'd70;
                10'h388: route_stop_led = 8'd114;
                10'h390: route_stop_led = 8'd142;
                10'h391: route_stop_led = 8'd11;
                10'h392: route_stop_led = 8'd1;
                10'h393: route_stop_led = 8'd78;
                10'h394: route_stop_led = 8'd25;
                10'h395: route_stop_led = 8'd21;
                10'h3A0: route_stop_led = 8'd106;
                10'h3A1: route_stop_led = 8'd33;
                10'h3A2: route_stop_led = 8'd65;
                10'h3A3: route_stop_led = 8'd58;
                10'h3A4: route_stop_led = 8'd95;
                10'h3A5: route_stop_led = 8'd44;
                10'h3A6: route_stop_led = 8'd50;
                10'h3A7: route_stop_led = 8'd70;
                10'h3A8: route_stop_led = 8'd78;
                10'h3B0: route_stop_led = 8'd142;
                10'h3B1: route_stop_led = 8'd11;
                10'h3B2: route_stop_led = 8'd1;
                10'h3B3: route_stop_led = 8'd114;
                10'h3B4: route_stop_led = 8'd25;
                10'h3B5: route_stop_led = 8'd21;
                10'h3C0: route_stop_led = 8'd106;
                10'h3C1: route_stop_led = 8'd33;
                10'h3C2: route_stop_led = 8'd65;
                10'h3C3: route_stop_led = 8'd58;
                10'h3C4: route_stop_led = 8'd95;
                10'h3C5: route_stop_led = 8'd44;
                10'h3C6: route_stop_led = 8'd50;
                10'h3C7: route_stop_led = 8'd70;
                10'h3C8: route_stop_led = 8'd114;
                10'h3D0: route_stop_led = 8'd142;
                10'h3D1: route_stop_led = 8'd11;
                10'h3D2: route_stop_led = 8'd1;
                10'h3D3: route_stop_led = 8'd25;
                10'h3D4: route_stop_led = 8'd21;
                10'h3D5: route_stop_led = 8'd78;
                10'h3E0: route_stop_led = 8'd106;
                10'h3E1: route_stop_led = 8'd70;
                10'h3E2: route_stop_led = 8'd33;
                10'h3E3: route_stop_led = 8'd65;
                10'h3E4: route_stop_led = 8'd58;
                10'h3E5: route_stop_led = 8'd95;
                10'h3E6: route_stop_led = 8'd44;
                10'h3E7: route_stop_led = 8'd50;
                10'h3E8: route_stop_led = 8'd142;
                10'h3E9: route_stop_led = 8'd114;
                10'h3F0: route_stop_led = 8'd106;
                default: route_stop_led = 8'd106;
            endcase
        end
    endfunction

    function [3:0] route_len;
        input [4:0] addr;
        input       bus;
        begin
            case ({addr, bus})
                6'h00: route_len = 4'd9;
                6'h01: route_len = 4'd6;
                6'h02: route_len = 4'd9;
                6'h03: route_len = 4'd6;
                6'h04: route_len = 4'd9;
                6'h05: route_len = 4'd6;
                6'h06: route_len = 4'd9;
                6'h07: route_len = 4'd6;
                6'h08: route_len = 4'd9;
                6'h09: route_len = 4'd6;
                6'h0A: route_len = 4'd9;
                6'h0B: route_len = 4'd6;
                6'h0C: route_len = 4'd9;
                6'h0D: route_len = 4'd6;
                6'h0E: route_len = 4'd9;
                6'h0F: route_len = 4'd1;
                6'h10: route_len = 4'd9;
                6'h11: route_len = 4'd6;
                6'h12: route_len = 4'd9;
                6'h13: route_len = 4'd6;
                6'h14: route_len = 4'd9;
                6'h15: route_len = 4'd6;
                6'h16: route_len = 4'd9;
                6'h17: route_len = 4'd6;
                6'h18: route_len = 4'd9;
                6'h19: route_len = 4'd6;
                6'h1A: route_len = 4'd9;
                6'h1B: route_len = 4'd6;
                6'h1C: route_len = 4'd9;
                6'h1D: route_len = 4'd6;
                6'h1E: route_len = 4'd9;
                6'h1F: route_len = 4'd4;
                6'h20: route_len = 4'd9;
                6'h21: route_len = 4'd4;
                6'h22: route_len = 4'd11;
                6'h23: route_len = 4'd4;
                6'h24: route_len = 4'd9;
                6'h25: route_len = 4'd6;
                6'h26: route_len = 4'd9;
                6'h27: route_len = 4'd4;
                6'h28: route_len = 4'd9;
                6'h29: route_len = 4'd6;
                6'h2A: route_len = 4'd9;
                6'h2B: route_len = 4'd5;
                6'h2C: route_len = 4'd9;
                6'h2D: route_len = 4'd4;
                6'h2E: route_len = 4'd9;
                6'h2F: route_len = 4'd1;
                6'h30: route_len = 4'd9;
                6'h31: route_len = 4'd6;
                6'h32: route_len = 4'd9;
                6'h33: route_len = 4'd6;
                6'h34: route_len = 4'd9;
                6'h35: route_len = 4'd6;
                6'h36: route_len = 4'd9;
                6'h37: route_len = 4'd6;
                6'h38: route_len = 4'd9;
                6'h39: route_len = 4'd6;
                6'h3A: route_len = 4'd9;
                6'h3B: route_len = 4'd6;
                6'h3C: route_len = 4'd9;
                6'h3D: route_len = 4'd6;
                6'h3E: route_len = 4'd10;
                6'h3F: route_len = 4'd1;
                default: route_len = 4'd1;
            endcase
        end
    endfunction

    // b2_stop_led(idx) -> LED number for bus 2 fixed all-stops circuit
    function [7:0] b2_stop_led;
        input [3:0] idx;
        begin
            case (idx)
                4'd 0: b2_stop_led = 8'd106;
                4'd 1: b2_stop_led = 8'd114;
                4'd 2: b2_stop_led = 8'd33;
                4'd 3: b2_stop_led = 8'd70;
                4'd 4: b2_stop_led = 8'd78;
                4'd 5: b2_stop_led = 8'd25;
                4'd 6: b2_stop_led = 8'd65;
                4'd 7: b2_stop_led = 8'd58;
                4'd 8: b2_stop_led = 8'd95;
                4'd 9: b2_stop_led = 8'd21;
                4'd10: b2_stop_led = 8'd50;
                4'd11: b2_stop_led = 8'd44;
                4'd12: b2_stop_led = 8'd142;
                4'd13: b2_stop_led = 8'd11;
                4'd14: b2_stop_led = 8'd1;
                default: b2_stop_led = 8'd106;
            endcase
        end
    endfunction

    // get_path_id(from_led, to_led) -> path_id
    function [7:0] get_path_id;
        input [7:0] from_led;
        input [7:0] to_led;
        begin
            case ({from_led, to_led})
                16'h0115: get_path_id = 8'd0;
                16'h0119: get_path_id = 8'd1;
                16'h0141: get_path_id = 8'd2;
                16'h014E: get_path_id = 8'd3;
                16'h016A: get_path_id = 8'd4;
                16'h0172: get_path_id = 8'd5;
                16'h0B01: get_path_id = 8'd6;
                16'h1519: get_path_id = 8'd7;
                16'h1532: get_path_id = 8'd8;
                16'h154E: get_path_id = 8'd9;
                16'h1572: get_path_id = 8'd10;
                16'h158E: get_path_id = 8'd11;
                16'h1915: get_path_id = 8'd12;
                16'h1941: get_path_id = 8'd13;
                16'h194E: get_path_id = 8'd14;
                16'h1972: get_path_id = 8'd15;
                16'h198E: get_path_id = 8'd16;
                16'h2141: get_path_id = 8'd17;
                16'h2146: get_path_id = 8'd18;
                16'h216A: get_path_id = 8'd19;
                16'h2C32: get_path_id = 8'd20;
                16'h2C8E: get_path_id = 8'd21;
                16'h322C: get_path_id = 8'd22;
                16'h3246: get_path_id = 8'd23;
                16'h328E: get_path_id = 8'd24;
                16'h3A2C: get_path_id = 8'd25;
                16'h3A5F: get_path_id = 8'd26;
                16'h4121: get_path_id = 8'd27;
                16'h413A: get_path_id = 8'd28;
                16'h415F: get_path_id = 8'd29;
                16'h4621: get_path_id = 8'd30;
                16'h464E: get_path_id = 8'd31;
                16'h465F: get_path_id = 8'd32;
                16'h4672: get_path_id = 8'd33;
                16'h4E15: get_path_id = 8'd34;
                16'h4E19: get_path_id = 8'd35;
                16'h4E6A: get_path_id = 8'd36;
                16'h4E72: get_path_id = 8'd37;
                16'h4E8E: get_path_id = 8'd38;
                16'h5F15: get_path_id = 8'd39;
                16'h5F2C: get_path_id = 8'd40;
                16'h5F3A: get_path_id = 8'd41;
                16'h6A21: get_path_id = 8'd42;
                16'h6A46: get_path_id = 8'd43;
                16'h6A72: get_path_id = 8'd44;
                16'h7219: get_path_id = 8'd45;
                16'h7221: get_path_id = 8'd46;
                16'h726A: get_path_id = 8'd47;
                16'h728E: get_path_id = 8'd48;
                16'h8E01: get_path_id = 8'd49;
                16'h8E0B: get_path_id = 8'd50;
                16'h8E19: get_path_id = 8'd51;
                16'h8E72: get_path_id = 8'd52;
                default: get_path_id = 8'd0;
            endcase
        end
    endfunction

    function [7:0] get_path_len;
        input [7:0] path_id;
        begin
            case (path_id)
                8'd0: get_path_len = 8'd21;
                8'd1: get_path_len = 8'd25;
                8'd2: get_path_len = 8'd23;
                8'd3: get_path_len = 8'd29;
                8'd4: get_path_len = 8'd35;
                8'd5: get_path_len = 8'd29;
                8'd6: get_path_len = 8'd11;
                8'd7: get_path_len = 8'd17;
                8'd8: get_path_len = 8'd7;
                8'd9: get_path_len = 8'd29;
                8'd10: get_path_len = 8'd21;
                8'd11: get_path_len = 8'd19;
                8'd12: get_path_len = 8'd17;
                8'd13: get_path_len = 8'd15;
                8'd14: get_path_len = 8'd29;
                8'd15: get_path_len = 8'd9;
                8'd16: get_path_len = 8'd25;
                8'd17: get_path_len = 8'd7;
                8'd18: get_path_len = 8'd21;
                8'd19: get_path_len = 8'd15;
                8'd20: get_path_len = 8'd7;
                8'd21: get_path_len = 8'd13;
                8'd22: get_path_len = 8'd7;
                8'd23: get_path_len = 8'd27;
                8'd24: get_path_len = 8'd15;
                8'd25: get_path_len = 8'd7;
                8'd26: get_path_len = 8'd11;
                8'd27: get_path_len = 8'd7;
                8'd28: get_path_len = 8'd13;
                8'd29: get_path_len = 8'd15;
                8'd30: get_path_len = 8'd21;
                8'd31: get_path_len = 8'd9;
                8'd32: get_path_len = 8'd13;
                8'd33: get_path_len = 8'd17;
                8'd34: get_path_len = 8'd29;
                8'd35: get_path_len = 8'd29;
                8'd36: get_path_len = 8'd11;
                8'd37: get_path_len = 8'd21;
                8'd38: get_path_len = 8'd29;
                8'd39: get_path_len = 8'd21;
                8'd40: get_path_len = 8'd9;
                8'd41: get_path_len = 8'd11;
                8'd42: get_path_len = 8'd15;
                8'd43: get_path_len = 8'd7;
                8'd44: get_path_len = 8'd11;
                8'd45: get_path_len = 8'd9;
                8'd46: get_path_len = 8'd9;
                8'd47: get_path_len = 8'd11;
                8'd48: get_path_len = 8'd29;
                8'd49: get_path_len = 8'd13;
                8'd50: get_path_len = 8'd13;
                8'd51: get_path_len = 8'd25;
                8'd52: get_path_len = 8'd29;
                default: get_path_len = 8'd1;
            endcase
        end
    endfunction

    // path_rom(path_id, step) -> LED  [max path=35]
    function [7:0] path_rom;
        input [7:0] path_id;
        input [7:0] step;
        begin
            case ({path_id, step})
                16'h0000: path_rom = 8'd1;
                16'h0001: path_rom = 8'd2;
                16'h0002: path_rom = 8'd3;
                16'h0003: path_rom = 8'd4;
                16'h0004: path_rom = 8'd5;
                16'h0005: path_rom = 8'd6;
                16'h0006: path_rom = 8'd7;
                16'h0007: path_rom = 8'd8;
                16'h0008: path_rom = 8'd9;
                16'h0009: path_rom = 8'd10;
                16'h000A: path_rom = 8'd11;
                16'h000B: path_rom = 8'd12;
                16'h000C: path_rom = 8'd13;
                16'h000D: path_rom = 8'd14;
                16'h000E: path_rom = 8'd15;
                16'h000F: path_rom = 8'd16;
                16'h0010: path_rom = 8'd17;
                16'h0011: path_rom = 8'd18;
                16'h0012: path_rom = 8'd19;
                16'h0013: path_rom = 8'd20;
                16'h0014: path_rom = 8'd21;
                16'h0100: path_rom = 8'd1;
                16'h0101: path_rom = 8'd153;
                16'h0102: path_rom = 8'd152;
                16'h0103: path_rom = 8'd151;
                16'h0104: path_rom = 8'd150;
                16'h0105: path_rom = 8'd149;
                16'h0106: path_rom = 8'd148;
                16'h0107: path_rom = 8'd64;
                16'h0108: path_rom = 8'd63;
                16'h0109: path_rom = 8'd62;
                16'h010A: path_rom = 8'd46;
                16'h010B: path_rom = 8'd47;
                16'h010C: path_rom = 8'd48;
                16'h010D: path_rom = 8'd49;
                16'h010E: path_rom = 8'd50;
                16'h010F: path_rom = 8'd131;
                16'h0110: path_rom = 8'd130;
                16'h0111: path_rom = 8'd129;
                16'h0112: path_rom = 8'd128;
                16'h0113: path_rom = 8'd127;
                16'h0114: path_rom = 8'd126;
                16'h0115: path_rom = 8'd22;
                16'h0116: path_rom = 8'd23;
                16'h0117: path_rom = 8'd24;
                16'h0118: path_rom = 8'd25;
                16'h0200: path_rom = 8'd1;
                16'h0201: path_rom = 8'd153;
                16'h0202: path_rom = 8'd152;
                16'h0203: path_rom = 8'd151;
                16'h0204: path_rom = 8'd150;
                16'h0205: path_rom = 8'd149;
                16'h0206: path_rom = 8'd148;
                16'h0207: path_rom = 8'd64;
                16'h0208: path_rom = 8'd63;
                16'h0209: path_rom = 8'd62;
                16'h020A: path_rom = 8'd46;
                16'h020B: path_rom = 8'd45;
                16'h020C: path_rom = 8'd44;
                16'h020D: path_rom = 8'd43;
                16'h020E: path_rom = 8'd89;
                16'h020F: path_rom = 8'd42;
                16'h0210: path_rom = 8'd41;
                16'h0211: path_rom = 8'd40;
                16'h0212: path_rom = 8'd39;
                16'h0213: path_rom = 8'd68;
                16'h0214: path_rom = 8'd67;
                16'h0215: path_rom = 8'd66;
                16'h0216: path_rom = 8'd65;
                16'h0300: path_rom = 8'd1;
                16'h0301: path_rom = 8'd153;
                16'h0302: path_rom = 8'd152;
                16'h0303: path_rom = 8'd151;
                16'h0304: path_rom = 8'd150;
                16'h0305: path_rom = 8'd149;
                16'h0306: path_rom = 8'd148;
                16'h0307: path_rom = 8'd64;
                16'h0308: path_rom = 8'd63;
                16'h0309: path_rom = 8'd62;
                16'h030A: path_rom = 8'd46;
                16'h030B: path_rom = 8'd45;
                16'h030C: path_rom = 8'd44;
                16'h030D: path_rom = 8'd43;
                16'h030E: path_rom = 8'd89;
                16'h030F: path_rom = 8'd90;
                16'h0310: path_rom = 8'd91;
                16'h0311: path_rom = 8'd92;
                16'h0312: path_rom = 8'd93;
                16'h0313: path_rom = 8'd94;
                16'h0314: path_rom = 8'd95;
                16'h0315: path_rom = 8'd85;
                16'h0316: path_rom = 8'd84;
                16'h0317: path_rom = 8'd83;
                16'h0318: path_rom = 8'd82;
                16'h0319: path_rom = 8'd81;
                16'h031A: path_rom = 8'd80;
                16'h031B: path_rom = 8'd79;
                16'h031C: path_rom = 8'd78;
                16'h0400: path_rom = 8'd1;
                16'h0401: path_rom = 8'd153;
                16'h0402: path_rom = 8'd152;
                16'h0403: path_rom = 8'd151;
                16'h0404: path_rom = 8'd150;
                16'h0405: path_rom = 8'd149;
                16'h0406: path_rom = 8'd148;
                16'h0407: path_rom = 8'd64;
                16'h0408: path_rom = 8'd63;
                16'h0409: path_rom = 8'd62;
                16'h040A: path_rom = 8'd46;
                16'h040B: path_rom = 8'd45;
                16'h040C: path_rom = 8'd44;
                16'h040D: path_rom = 8'd43;
                16'h040E: path_rom = 8'd89;
                16'h040F: path_rom = 8'd90;
                16'h0410: path_rom = 8'd91;
                16'h0411: path_rom = 8'd92;
                16'h0412: path_rom = 8'd93;
                16'h0413: path_rom = 8'd94;
                16'h0414: path_rom = 8'd95;
                16'h0415: path_rom = 8'd96;
                16'h0416: path_rom = 8'd97;
                16'h0417: path_rom = 8'd98;
                16'h0418: path_rom = 8'd99;
                16'h0419: path_rom = 8'd100;
                16'h041A: path_rom = 8'd101;
                16'h041B: path_rom = 8'd102;
                16'h041C: path_rom = 8'd74;
                16'h041D: path_rom = 8'd73;
                16'h041E: path_rom = 8'd72;
                16'h041F: path_rom = 8'd103;
                16'h0420: path_rom = 8'd104;
                16'h0421: path_rom = 8'd105;
                16'h0422: path_rom = 8'd106;
                16'h0500: path_rom = 8'd1;
                16'h0501: path_rom = 8'd153;
                16'h0502: path_rom = 8'd152;
                16'h0503: path_rom = 8'd151;
                16'h0504: path_rom = 8'd150;
                16'h0505: path_rom = 8'd149;
                16'h0506: path_rom = 8'd148;
                16'h0507: path_rom = 8'd64;
                16'h0508: path_rom = 8'd63;
                16'h0509: path_rom = 8'd62;
                16'h050A: path_rom = 8'd46;
                16'h050B: path_rom = 8'd47;
                16'h050C: path_rom = 8'd48;
                16'h050D: path_rom = 8'd49;
                16'h050E: path_rom = 8'd50;
                16'h050F: path_rom = 8'd131;
                16'h0510: path_rom = 8'd130;
                16'h0511: path_rom = 8'd129;
                16'h0512: path_rom = 8'd128;
                16'h0513: path_rom = 8'd127;
                16'h0514: path_rom = 8'd126;
                16'h0515: path_rom = 8'd125;
                16'h0516: path_rom = 8'd31;
                16'h0517: path_rom = 8'd30;
                16'h0518: path_rom = 8'd29;
                16'h0519: path_rom = 8'd124;
                16'h051A: path_rom = 8'd123;
                16'h051B: path_rom = 8'd122;
                16'h051C: path_rom = 8'd114;
                16'h0600: path_rom = 8'd11;
                16'h0601: path_rom = 8'd10;
                16'h0602: path_rom = 8'd9;
                16'h0603: path_rom = 8'd8;
                16'h0604: path_rom = 8'd7;
                16'h0605: path_rom = 8'd6;
                16'h0606: path_rom = 8'd5;
                16'h0607: path_rom = 8'd4;
                16'h0608: path_rom = 8'd3;
                16'h0609: path_rom = 8'd2;
                16'h060A: path_rom = 8'd1;
                16'h0700: path_rom = 8'd21;
                16'h0701: path_rom = 8'd20;
                16'h0702: path_rom = 8'd19;
                16'h0703: path_rom = 8'd53;
                16'h0704: path_rom = 8'd52;
                16'h0705: path_rom = 8'd51;
                16'h0706: path_rom = 8'd50;
                16'h0707: path_rom = 8'd131;
                16'h0708: path_rom = 8'd130;
                16'h0709: path_rom = 8'd129;
                16'h070A: path_rom = 8'd128;
                16'h070B: path_rom = 8'd127;
                16'h070C: path_rom = 8'd126;
                16'h070D: path_rom = 8'd22;
                16'h070E: path_rom = 8'd23;
                16'h070F: path_rom = 8'd24;
                16'h0710: path_rom = 8'd25;
                16'h0800: path_rom = 8'd21;
                16'h0801: path_rom = 8'd20;
                16'h0802: path_rom = 8'd19;
                16'h0803: path_rom = 8'd53;
                16'h0804: path_rom = 8'd52;
                16'h0805: path_rom = 8'd51;
                16'h0806: path_rom = 8'd50;
                16'h0900: path_rom = 8'd21;
                16'h0901: path_rom = 8'd20;
                16'h0902: path_rom = 8'd19;
                16'h0903: path_rom = 8'd53;
                16'h0904: path_rom = 8'd52;
                16'h0905: path_rom = 8'd51;
                16'h0906: path_rom = 8'd50;
                16'h0907: path_rom = 8'd49;
                16'h0908: path_rom = 8'd48;
                16'h0909: path_rom = 8'd47;
                16'h090A: path_rom = 8'd46;
                16'h090B: path_rom = 8'd45;
                16'h090C: path_rom = 8'd44;
                16'h090D: path_rom = 8'd43;
                16'h090E: path_rom = 8'd89;
                16'h090F: path_rom = 8'd90;
                16'h0910: path_rom = 8'd91;
                16'h0911: path_rom = 8'd92;
                16'h0912: path_rom = 8'd93;
                16'h0913: path_rom = 8'd94;
                16'h0914: path_rom = 8'd95;
                16'h0915: path_rom = 8'd85;
                16'h0916: path_rom = 8'd84;
                16'h0917: path_rom = 8'd83;
                16'h0918: path_rom = 8'd82;
                16'h0919: path_rom = 8'd81;
                16'h091A: path_rom = 8'd80;
                16'h091B: path_rom = 8'd79;
                16'h091C: path_rom = 8'd78;
                16'h0A00: path_rom = 8'd21;
                16'h0A01: path_rom = 8'd20;
                16'h0A02: path_rom = 8'd19;
                16'h0A03: path_rom = 8'd53;
                16'h0A04: path_rom = 8'd52;
                16'h0A05: path_rom = 8'd51;
                16'h0A06: path_rom = 8'd50;
                16'h0A07: path_rom = 8'd131;
                16'h0A08: path_rom = 8'd130;
                16'h0A09: path_rom = 8'd129;
                16'h0A0A: path_rom = 8'd128;
                16'h0A0B: path_rom = 8'd127;
                16'h0A0C: path_rom = 8'd126;
                16'h0A0D: path_rom = 8'd125;
                16'h0A0E: path_rom = 8'd31;
                16'h0A0F: path_rom = 8'd30;
                16'h0A10: path_rom = 8'd29;
                16'h0A11: path_rom = 8'd124;
                16'h0A12: path_rom = 8'd123;
                16'h0A13: path_rom = 8'd122;
                16'h0A14: path_rom = 8'd114;
                16'h0B00: path_rom = 8'd21;
                16'h0B01: path_rom = 8'd20;
                16'h0B02: path_rom = 8'd19;
                16'h0B03: path_rom = 8'd18;
                16'h0B04: path_rom = 8'd17;
                16'h0B05: path_rom = 8'd16;
                16'h0B06: path_rom = 8'd15;
                16'h0B07: path_rom = 8'd14;
                16'h0B08: path_rom = 8'd13;
                16'h0B09: path_rom = 8'd141;
                16'h0B0A: path_rom = 8'd140;
                16'h0B0B: path_rom = 8'd139;
                16'h0B0C: path_rom = 8'd138;
                16'h0B0D: path_rom = 8'd137;
                16'h0B0E: path_rom = 8'd146;
                16'h0B0F: path_rom = 8'd145;
                16'h0B10: path_rom = 8'd144;
                16'h0B11: path_rom = 8'd143;
                16'h0B12: path_rom = 8'd142;
                16'h0C00: path_rom = 8'd25;
                16'h0C01: path_rom = 8'd24;
                16'h0C02: path_rom = 8'd23;
                16'h0C03: path_rom = 8'd22;
                16'h0C04: path_rom = 8'd126;
                16'h0C05: path_rom = 8'd127;
                16'h0C06: path_rom = 8'd128;
                16'h0C07: path_rom = 8'd129;
                16'h0C08: path_rom = 8'd130;
                16'h0C09: path_rom = 8'd131;
                16'h0C0A: path_rom = 8'd50;
                16'h0C0B: path_rom = 8'd51;
                16'h0C0C: path_rom = 8'd52;
                16'h0C0D: path_rom = 8'd53;
                16'h0C0E: path_rom = 8'd19;
                16'h0C0F: path_rom = 8'd20;
                16'h0C10: path_rom = 8'd21;
                16'h0D00: path_rom = 8'd25;
                16'h0D01: path_rom = 8'd24;
                16'h0D02: path_rom = 8'd23;
                16'h0D03: path_rom = 8'd22;
                16'h0D04: path_rom = 8'd126;
                16'h0D05: path_rom = 8'd125;
                16'h0D06: path_rom = 8'd31;
                16'h0D07: path_rom = 8'd32;
                16'h0D08: path_rom = 8'd33;
                16'h0D09: path_rom = 8'd34;
                16'h0D0A: path_rom = 8'd35;
                16'h0D0B: path_rom = 8'd69;
                16'h0D0C: path_rom = 8'd67;
                16'h0D0D: path_rom = 8'd66;
                16'h0D0E: path_rom = 8'd65;
                16'h0E00: path_rom = 8'd25;
                16'h0E01: path_rom = 8'd24;
                16'h0E02: path_rom = 8'd23;
                16'h0E03: path_rom = 8'd22;
                16'h0E04: path_rom = 8'd126;
                16'h0E05: path_rom = 8'd127;
                16'h0E06: path_rom = 8'd128;
                16'h0E07: path_rom = 8'd55;
                16'h0E08: path_rom = 8'd56;
                16'h0E09: path_rom = 8'd57;
                16'h0E0A: path_rom = 8'd58;
                16'h0E0B: path_rom = 8'd59;
                16'h0E0C: path_rom = 8'd60;
                16'h0E0D: path_rom = 8'd88;
                16'h0E0E: path_rom = 8'd89;
                16'h0E0F: path_rom = 8'd90;
                16'h0E10: path_rom = 8'd91;
                16'h0E11: path_rom = 8'd92;
                16'h0E12: path_rom = 8'd93;
                16'h0E13: path_rom = 8'd94;
                16'h0E14: path_rom = 8'd95;
                16'h0E15: path_rom = 8'd85;
                16'h0E16: path_rom = 8'd84;
                16'h0E17: path_rom = 8'd83;
                16'h0E18: path_rom = 8'd82;
                16'h0E19: path_rom = 8'd81;
                16'h0E1A: path_rom = 8'd80;
                16'h0E1B: path_rom = 8'd79;
                16'h0E1C: path_rom = 8'd78;
                16'h0F00: path_rom = 8'd25;
                16'h0F01: path_rom = 8'd26;
                16'h0F02: path_rom = 8'd27;
                16'h0F03: path_rom = 8'd28;
                16'h0F04: path_rom = 8'd29;
                16'h0F05: path_rom = 8'd124;
                16'h0F06: path_rom = 8'd123;
                16'h0F07: path_rom = 8'd122;
                16'h0F08: path_rom = 8'd114;
                16'h1000: path_rom = 8'd25;
                16'h1001: path_rom = 8'd24;
                16'h1002: path_rom = 8'd23;
                16'h1003: path_rom = 8'd22;
                16'h1004: path_rom = 8'd126;
                16'h1005: path_rom = 8'd127;
                16'h1006: path_rom = 8'd128;
                16'h1007: path_rom = 8'd55;
                16'h1008: path_rom = 8'd56;
                16'h1009: path_rom = 8'd57;
                16'h100A: path_rom = 8'd58;
                16'h100B: path_rom = 8'd59;
                16'h100C: path_rom = 8'd60;
                16'h100D: path_rom = 8'd61;
                16'h100E: path_rom = 8'd46;
                16'h100F: path_rom = 8'd62;
                16'h1010: path_rom = 8'd63;
                16'h1011: path_rom = 8'd64;
                16'h1012: path_rom = 8'd148;
                16'h1013: path_rom = 8'd147;
                16'h1014: path_rom = 8'd146;
                16'h1015: path_rom = 8'd145;
                16'h1016: path_rom = 8'd144;
                16'h1017: path_rom = 8'd143;
                16'h1018: path_rom = 8'd142;
                16'h1100: path_rom = 8'd33;
                16'h1101: path_rom = 8'd34;
                16'h1102: path_rom = 8'd35;
                16'h1103: path_rom = 8'd69;
                16'h1104: path_rom = 8'd67;
                16'h1105: path_rom = 8'd66;
                16'h1106: path_rom = 8'd65;
                16'h1200: path_rom = 8'd33;
                16'h1201: path_rom = 8'd121;
                16'h1202: path_rom = 8'd120;
                16'h1203: path_rom = 8'd119;
                16'h1204: path_rom = 8'd118;
                16'h1205: path_rom = 8'd117;
                16'h1206: path_rom = 8'd116;
                16'h1207: path_rom = 8'd113;
                16'h1208: path_rom = 8'd112;
                16'h1209: path_rom = 8'd111;
                16'h120A: path_rom = 8'd110;
                16'h120B: path_rom = 8'd109;
                16'h120C: path_rom = 8'd108;
                16'h120D: path_rom = 8'd107;
                16'h120E: path_rom = 8'd106;
                16'h120F: path_rom = 8'd105;
                16'h1210: path_rom = 8'd104;
                16'h1211: path_rom = 8'd103;
                16'h1212: path_rom = 8'd72;
                16'h1213: path_rom = 8'd71;
                16'h1214: path_rom = 8'd70;
                16'h1300: path_rom = 8'd33;
                16'h1301: path_rom = 8'd121;
                16'h1302: path_rom = 8'd120;
                16'h1303: path_rom = 8'd119;
                16'h1304: path_rom = 8'd118;
                16'h1305: path_rom = 8'd117;
                16'h1306: path_rom = 8'd116;
                16'h1307: path_rom = 8'd113;
                16'h1308: path_rom = 8'd112;
                16'h1309: path_rom = 8'd111;
                16'h130A: path_rom = 8'd110;
                16'h130B: path_rom = 8'd109;
                16'h130C: path_rom = 8'd108;
                16'h130D: path_rom = 8'd107;
                16'h130E: path_rom = 8'd106;
                16'h1400: path_rom = 8'd44;
                16'h1401: path_rom = 8'd45;
                16'h1402: path_rom = 8'd46;
                16'h1403: path_rom = 8'd47;
                16'h1404: path_rom = 8'd48;
                16'h1405: path_rom = 8'd49;
                16'h1406: path_rom = 8'd50;
                16'h1500: path_rom = 8'd44;
                16'h1501: path_rom = 8'd45;
                16'h1502: path_rom = 8'd46;
                16'h1503: path_rom = 8'd62;
                16'h1504: path_rom = 8'd63;
                16'h1505: path_rom = 8'd64;
                16'h1506: path_rom = 8'd148;
                16'h1507: path_rom = 8'd147;
                16'h1508: path_rom = 8'd146;
                16'h1509: path_rom = 8'd145;
                16'h150A: path_rom = 8'd144;
                16'h150B: path_rom = 8'd143;
                16'h150C: path_rom = 8'd142;
                16'h1600: path_rom = 8'd50;
                16'h1601: path_rom = 8'd49;
                16'h1602: path_rom = 8'd48;
                16'h1603: path_rom = 8'd47;
                16'h1604: path_rom = 8'd46;
                16'h1605: path_rom = 8'd45;
                16'h1606: path_rom = 8'd44;
                16'h1700: path_rom = 8'd50;
                16'h1701: path_rom = 8'd49;
                16'h1702: path_rom = 8'd48;
                16'h1703: path_rom = 8'd47;
                16'h1704: path_rom = 8'd46;
                16'h1705: path_rom = 8'd45;
                16'h1706: path_rom = 8'd44;
                16'h1707: path_rom = 8'd43;
                16'h1708: path_rom = 8'd89;
                16'h1709: path_rom = 8'd90;
                16'h170A: path_rom = 8'd91;
                16'h170B: path_rom = 8'd92;
                16'h170C: path_rom = 8'd93;
                16'h170D: path_rom = 8'd94;
                16'h170E: path_rom = 8'd95;
                16'h170F: path_rom = 8'd96;
                16'h1710: path_rom = 8'd97;
                16'h1711: path_rom = 8'd98;
                16'h1712: path_rom = 8'd99;
                16'h1713: path_rom = 8'd100;
                16'h1714: path_rom = 8'd101;
                16'h1715: path_rom = 8'd102;
                16'h1716: path_rom = 8'd74;
                16'h1717: path_rom = 8'd73;
                16'h1718: path_rom = 8'd72;
                16'h1719: path_rom = 8'd71;
                16'h171A: path_rom = 8'd70;
                16'h1800: path_rom = 8'd50;
                16'h1801: path_rom = 8'd49;
                16'h1802: path_rom = 8'd48;
                16'h1803: path_rom = 8'd47;
                16'h1804: path_rom = 8'd46;
                16'h1805: path_rom = 8'd62;
                16'h1806: path_rom = 8'd63;
                16'h1807: path_rom = 8'd64;
                16'h1808: path_rom = 8'd148;
                16'h1809: path_rom = 8'd147;
                16'h180A: path_rom = 8'd146;
                16'h180B: path_rom = 8'd145;
                16'h180C: path_rom = 8'd144;
                16'h180D: path_rom = 8'd143;
                16'h180E: path_rom = 8'd142;
                16'h1900: path_rom = 8'd58;
                16'h1901: path_rom = 8'd59;
                16'h1902: path_rom = 8'd60;
                16'h1903: path_rom = 8'd61;
                16'h1904: path_rom = 8'd46;
                16'h1905: path_rom = 8'd45;
                16'h1906: path_rom = 8'd44;
                16'h1A00: path_rom = 8'd58;
                16'h1A01: path_rom = 8'd59;
                16'h1A02: path_rom = 8'd60;
                16'h1A03: path_rom = 8'd88;
                16'h1A04: path_rom = 8'd89;
                16'h1A05: path_rom = 8'd90;
                16'h1A06: path_rom = 8'd91;
                16'h1A07: path_rom = 8'd92;
                16'h1A08: path_rom = 8'd93;
                16'h1A09: path_rom = 8'd94;
                16'h1A0A: path_rom = 8'd95;
                16'h1B00: path_rom = 8'd65;
                16'h1B01: path_rom = 8'd66;
                16'h1B02: path_rom = 8'd67;
                16'h1B03: path_rom = 8'd69;
                16'h1B04: path_rom = 8'd35;
                16'h1B05: path_rom = 8'd34;
                16'h1B06: path_rom = 8'd33;
                16'h1C00: path_rom = 8'd65;
                16'h1C01: path_rom = 8'd66;
                16'h1C02: path_rom = 8'd67;
                16'h1C03: path_rom = 8'd68;
                16'h1C04: path_rom = 8'd39;
                16'h1C05: path_rom = 8'd40;
                16'h1C06: path_rom = 8'd41;
                16'h1C07: path_rom = 8'd42;
                16'h1C08: path_rom = 8'd89;
                16'h1C09: path_rom = 8'd88;
                16'h1C0A: path_rom = 8'd60;
                16'h1C0B: path_rom = 8'd59;
                16'h1C0C: path_rom = 8'd58;
                16'h1D00: path_rom = 8'd65;
                16'h1D01: path_rom = 8'd66;
                16'h1D02: path_rom = 8'd67;
                16'h1D03: path_rom = 8'd68;
                16'h1D04: path_rom = 8'd39;
                16'h1D05: path_rom = 8'd40;
                16'h1D06: path_rom = 8'd41;
                16'h1D07: path_rom = 8'd42;
                16'h1D08: path_rom = 8'd89;
                16'h1D09: path_rom = 8'd90;
                16'h1D0A: path_rom = 8'd91;
                16'h1D0B: path_rom = 8'd92;
                16'h1D0C: path_rom = 8'd93;
                16'h1D0D: path_rom = 8'd94;
                16'h1D0E: path_rom = 8'd95;
                16'h1E00: path_rom = 8'd70;
                16'h1E01: path_rom = 8'd71;
                16'h1E02: path_rom = 8'd72;
                16'h1E03: path_rom = 8'd103;
                16'h1E04: path_rom = 8'd104;
                16'h1E05: path_rom = 8'd105;
                16'h1E06: path_rom = 8'd106;
                16'h1E07: path_rom = 8'd107;
                16'h1E08: path_rom = 8'd108;
                16'h1E09: path_rom = 8'd109;
                16'h1E0A: path_rom = 8'd110;
                16'h1E0B: path_rom = 8'd111;
                16'h1E0C: path_rom = 8'd112;
                16'h1E0D: path_rom = 8'd113;
                16'h1E0E: path_rom = 8'd116;
                16'h1E0F: path_rom = 8'd117;
                16'h1E10: path_rom = 8'd118;
                16'h1E11: path_rom = 8'd119;
                16'h1E12: path_rom = 8'd120;
                16'h1E13: path_rom = 8'd121;
                16'h1E14: path_rom = 8'd33;
                16'h1F00: path_rom = 8'd70;
                16'h1F01: path_rom = 8'd71;
                16'h1F02: path_rom = 8'd72;
                16'h1F03: path_rom = 8'd73;
                16'h1F04: path_rom = 8'd74;
                16'h1F05: path_rom = 8'd75;
                16'h1F06: path_rom = 8'd76;
                16'h1F07: path_rom = 8'd77;
                16'h1F08: path_rom = 8'd78;
                16'h2000: path_rom = 8'd70;
                16'h2001: path_rom = 8'd71;
                16'h2002: path_rom = 8'd72;
                16'h2003: path_rom = 8'd73;
                16'h2004: path_rom = 8'd74;
                16'h2005: path_rom = 8'd102;
                16'h2006: path_rom = 8'd101;
                16'h2007: path_rom = 8'd100;
                16'h2008: path_rom = 8'd99;
                16'h2009: path_rom = 8'd98;
                16'h200A: path_rom = 8'd97;
                16'h200B: path_rom = 8'd96;
                16'h200C: path_rom = 8'd95;
                16'h2100: path_rom = 8'd70;
                16'h2101: path_rom = 8'd71;
                16'h2102: path_rom = 8'd72;
                16'h2103: path_rom = 8'd103;
                16'h2104: path_rom = 8'd104;
                16'h2105: path_rom = 8'd105;
                16'h2106: path_rom = 8'd106;
                16'h2107: path_rom = 8'd107;
                16'h2108: path_rom = 8'd108;
                16'h2109: path_rom = 8'd109;
                16'h210A: path_rom = 8'd110;
                16'h210B: path_rom = 8'd111;
                16'h210C: path_rom = 8'd112;
                16'h210D: path_rom = 8'd113;
                16'h210E: path_rom = 8'd116;
                16'h210F: path_rom = 8'd115;
                16'h2110: path_rom = 8'd114;
                16'h2200: path_rom = 8'd78;
                16'h2201: path_rom = 8'd79;
                16'h2202: path_rom = 8'd80;
                16'h2203: path_rom = 8'd81;
                16'h2204: path_rom = 8'd82;
                16'h2205: path_rom = 8'd83;
                16'h2206: path_rom = 8'd84;
                16'h2207: path_rom = 8'd85;
                16'h2208: path_rom = 8'd95;
                16'h2209: path_rom = 8'd94;
                16'h220A: path_rom = 8'd93;
                16'h220B: path_rom = 8'd92;
                16'h220C: path_rom = 8'd91;
                16'h220D: path_rom = 8'd90;
                16'h220E: path_rom = 8'd89;
                16'h220F: path_rom = 8'd43;
                16'h2210: path_rom = 8'd44;
                16'h2211: path_rom = 8'd45;
                16'h2212: path_rom = 8'd46;
                16'h2213: path_rom = 8'd47;
                16'h2214: path_rom = 8'd48;
                16'h2215: path_rom = 8'd49;
                16'h2216: path_rom = 8'd50;
                16'h2217: path_rom = 8'd51;
                16'h2218: path_rom = 8'd52;
                16'h2219: path_rom = 8'd53;
                16'h221A: path_rom = 8'd19;
                16'h221B: path_rom = 8'd20;
                16'h221C: path_rom = 8'd21;
                16'h2300: path_rom = 8'd78;
                16'h2301: path_rom = 8'd77;
                16'h2302: path_rom = 8'd76;
                16'h2303: path_rom = 8'd75;
                16'h2304: path_rom = 8'd74;
                16'h2305: path_rom = 8'd73;
                16'h2306: path_rom = 8'd72;
                16'h2307: path_rom = 8'd103;
                16'h2308: path_rom = 8'd104;
                16'h2309: path_rom = 8'd105;
                16'h230A: path_rom = 8'd106;
                16'h230B: path_rom = 8'd107;
                16'h230C: path_rom = 8'd108;
                16'h230D: path_rom = 8'd109;
                16'h230E: path_rom = 8'd110;
                16'h230F: path_rom = 8'd111;
                16'h2310: path_rom = 8'd112;
                16'h2311: path_rom = 8'd113;
                16'h2312: path_rom = 8'd116;
                16'h2313: path_rom = 8'd115;
                16'h2314: path_rom = 8'd114;
                16'h2315: path_rom = 8'd122;
                16'h2316: path_rom = 8'd123;
                16'h2317: path_rom = 8'd124;
                16'h2318: path_rom = 8'd29;
                16'h2319: path_rom = 8'd28;
                16'h231A: path_rom = 8'd27;
                16'h231B: path_rom = 8'd26;
                16'h231C: path_rom = 8'd25;
                16'h2400: path_rom = 8'd78;
                16'h2401: path_rom = 8'd77;
                16'h2402: path_rom = 8'd76;
                16'h2403: path_rom = 8'd75;
                16'h2404: path_rom = 8'd74;
                16'h2405: path_rom = 8'd73;
                16'h2406: path_rom = 8'd72;
                16'h2407: path_rom = 8'd103;
                16'h2408: path_rom = 8'd104;
                16'h2409: path_rom = 8'd105;
                16'h240A: path_rom = 8'd106;
                16'h2500: path_rom = 8'd78;
                16'h2501: path_rom = 8'd77;
                16'h2502: path_rom = 8'd76;
                16'h2503: path_rom = 8'd75;
                16'h2504: path_rom = 8'd74;
                16'h2505: path_rom = 8'd73;
                16'h2506: path_rom = 8'd72;
                16'h2507: path_rom = 8'd103;
                16'h2508: path_rom = 8'd104;
                16'h2509: path_rom = 8'd105;
                16'h250A: path_rom = 8'd106;
                16'h250B: path_rom = 8'd107;
                16'h250C: path_rom = 8'd108;
                16'h250D: path_rom = 8'd109;
                16'h250E: path_rom = 8'd110;
                16'h250F: path_rom = 8'd111;
                16'h2510: path_rom = 8'd112;
                16'h2511: path_rom = 8'd113;
                16'h2512: path_rom = 8'd116;
                16'h2513: path_rom = 8'd115;
                16'h2514: path_rom = 8'd114;
                16'h2600: path_rom = 8'd78;
                16'h2601: path_rom = 8'd79;
                16'h2602: path_rom = 8'd80;
                16'h2603: path_rom = 8'd81;
                16'h2604: path_rom = 8'd82;
                16'h2605: path_rom = 8'd83;
                16'h2606: path_rom = 8'd84;
                16'h2607: path_rom = 8'd85;
                16'h2608: path_rom = 8'd95;
                16'h2609: path_rom = 8'd94;
                16'h260A: path_rom = 8'd93;
                16'h260B: path_rom = 8'd92;
                16'h260C: path_rom = 8'd91;
                16'h260D: path_rom = 8'd90;
                16'h260E: path_rom = 8'd89;
                16'h260F: path_rom = 8'd43;
                16'h2610: path_rom = 8'd44;
                16'h2611: path_rom = 8'd45;
                16'h2612: path_rom = 8'd46;
                16'h2613: path_rom = 8'd62;
                16'h2614: path_rom = 8'd63;
                16'h2615: path_rom = 8'd64;
                16'h2616: path_rom = 8'd148;
                16'h2617: path_rom = 8'd147;
                16'h2618: path_rom = 8'd146;
                16'h2619: path_rom = 8'd145;
                16'h261A: path_rom = 8'd144;
                16'h261B: path_rom = 8'd143;
                16'h261C: path_rom = 8'd142;
                16'h2700: path_rom = 8'd95;
                16'h2701: path_rom = 8'd94;
                16'h2702: path_rom = 8'd93;
                16'h2703: path_rom = 8'd92;
                16'h2704: path_rom = 8'd91;
                16'h2705: path_rom = 8'd90;
                16'h2706: path_rom = 8'd89;
                16'h2707: path_rom = 8'd43;
                16'h2708: path_rom = 8'd44;
                16'h2709: path_rom = 8'd45;
                16'h270A: path_rom = 8'd46;
                16'h270B: path_rom = 8'd47;
                16'h270C: path_rom = 8'd48;
                16'h270D: path_rom = 8'd49;
                16'h270E: path_rom = 8'd50;
                16'h270F: path_rom = 8'd51;
                16'h2710: path_rom = 8'd52;
                16'h2711: path_rom = 8'd53;
                16'h2712: path_rom = 8'd19;
                16'h2713: path_rom = 8'd20;
                16'h2714: path_rom = 8'd21;
                16'h2800: path_rom = 8'd95;
                16'h2801: path_rom = 8'd94;
                16'h2802: path_rom = 8'd93;
                16'h2803: path_rom = 8'd92;
                16'h2804: path_rom = 8'd91;
                16'h2805: path_rom = 8'd90;
                16'h2806: path_rom = 8'd89;
                16'h2807: path_rom = 8'd43;
                16'h2808: path_rom = 8'd44;
                16'h2900: path_rom = 8'd95;
                16'h2901: path_rom = 8'd94;
                16'h2902: path_rom = 8'd93;
                16'h2903: path_rom = 8'd92;
                16'h2904: path_rom = 8'd91;
                16'h2905: path_rom = 8'd90;
                16'h2906: path_rom = 8'd89;
                16'h2907: path_rom = 8'd88;
                16'h2908: path_rom = 8'd60;
                16'h2909: path_rom = 8'd59;
                16'h290A: path_rom = 8'd58;
                16'h2A00: path_rom = 8'd106;
                16'h2A01: path_rom = 8'd107;
                16'h2A02: path_rom = 8'd108;
                16'h2A03: path_rom = 8'd109;
                16'h2A04: path_rom = 8'd110;
                16'h2A05: path_rom = 8'd111;
                16'h2A06: path_rom = 8'd112;
                16'h2A07: path_rom = 8'd113;
                16'h2A08: path_rom = 8'd116;
                16'h2A09: path_rom = 8'd117;
                16'h2A0A: path_rom = 8'd118;
                16'h2A0B: path_rom = 8'd119;
                16'h2A0C: path_rom = 8'd120;
                16'h2A0D: path_rom = 8'd121;
                16'h2A0E: path_rom = 8'd33;
                16'h2B00: path_rom = 8'd106;
                16'h2B01: path_rom = 8'd105;
                16'h2B02: path_rom = 8'd104;
                16'h2B03: path_rom = 8'd103;
                16'h2B04: path_rom = 8'd72;
                16'h2B05: path_rom = 8'd71;
                16'h2B06: path_rom = 8'd70;
                16'h2C00: path_rom = 8'd106;
                16'h2C01: path_rom = 8'd107;
                16'h2C02: path_rom = 8'd108;
                16'h2C03: path_rom = 8'd109;
                16'h2C04: path_rom = 8'd110;
                16'h2C05: path_rom = 8'd111;
                16'h2C06: path_rom = 8'd112;
                16'h2C07: path_rom = 8'd113;
                16'h2C08: path_rom = 8'd116;
                16'h2C09: path_rom = 8'd115;
                16'h2C0A: path_rom = 8'd114;
                16'h2D00: path_rom = 8'd114;
                16'h2D01: path_rom = 8'd122;
                16'h2D02: path_rom = 8'd123;
                16'h2D03: path_rom = 8'd124;
                16'h2D04: path_rom = 8'd29;
                16'h2D05: path_rom = 8'd28;
                16'h2D06: path_rom = 8'd27;
                16'h2D07: path_rom = 8'd26;
                16'h2D08: path_rom = 8'd25;
                16'h2E00: path_rom = 8'd114;
                16'h2E01: path_rom = 8'd115;
                16'h2E02: path_rom = 8'd116;
                16'h2E03: path_rom = 8'd117;
                16'h2E04: path_rom = 8'd118;
                16'h2E05: path_rom = 8'd119;
                16'h2E06: path_rom = 8'd120;
                16'h2E07: path_rom = 8'd121;
                16'h2E08: path_rom = 8'd33;
                16'h2F00: path_rom = 8'd114;
                16'h2F01: path_rom = 8'd115;
                16'h2F02: path_rom = 8'd116;
                16'h2F03: path_rom = 8'd113;
                16'h2F04: path_rom = 8'd112;
                16'h2F05: path_rom = 8'd111;
                16'h2F06: path_rom = 8'd110;
                16'h2F07: path_rom = 8'd109;
                16'h2F08: path_rom = 8'd108;
                16'h2F09: path_rom = 8'd107;
                16'h2F0A: path_rom = 8'd106;
                16'h3000: path_rom = 8'd114;
                16'h3001: path_rom = 8'd122;
                16'h3002: path_rom = 8'd123;
                16'h3003: path_rom = 8'd124;
                16'h3004: path_rom = 8'd29;
                16'h3005: path_rom = 8'd30;
                16'h3006: path_rom = 8'd31;
                16'h3007: path_rom = 8'd125;
                16'h3008: path_rom = 8'd126;
                16'h3009: path_rom = 8'd127;
                16'h300A: path_rom = 8'd128;
                16'h300B: path_rom = 8'd55;
                16'h300C: path_rom = 8'd56;
                16'h300D: path_rom = 8'd57;
                16'h300E: path_rom = 8'd58;
                16'h300F: path_rom = 8'd59;
                16'h3010: path_rom = 8'd60;
                16'h3011: path_rom = 8'd61;
                16'h3012: path_rom = 8'd46;
                16'h3013: path_rom = 8'd62;
                16'h3014: path_rom = 8'd63;
                16'h3015: path_rom = 8'd64;
                16'h3016: path_rom = 8'd148;
                16'h3017: path_rom = 8'd147;
                16'h3018: path_rom = 8'd146;
                16'h3019: path_rom = 8'd145;
                16'h301A: path_rom = 8'd144;
                16'h301B: path_rom = 8'd143;
                16'h301C: path_rom = 8'd142;
                16'h3100: path_rom = 8'd142;
                16'h3101: path_rom = 8'd143;
                16'h3102: path_rom = 8'd144;
                16'h3103: path_rom = 8'd145;
                16'h3104: path_rom = 8'd146;
                16'h3105: path_rom = 8'd147;
                16'h3106: path_rom = 8'd148;
                16'h3107: path_rom = 8'd149;
                16'h3108: path_rom = 8'd150;
                16'h3109: path_rom = 8'd151;
                16'h310A: path_rom = 8'd152;
                16'h310B: path_rom = 8'd153;
                16'h310C: path_rom = 8'd1;
                16'h3200: path_rom = 8'd142;
                16'h3201: path_rom = 8'd143;
                16'h3202: path_rom = 8'd144;
                16'h3203: path_rom = 8'd145;
                16'h3204: path_rom = 8'd146;
                16'h3205: path_rom = 8'd137;
                16'h3206: path_rom = 8'd138;
                16'h3207: path_rom = 8'd139;
                16'h3208: path_rom = 8'd140;
                16'h3209: path_rom = 8'd141;
                16'h320A: path_rom = 8'd13;
                16'h320B: path_rom = 8'd12;
                16'h320C: path_rom = 8'd11;
                16'h3300: path_rom = 8'd142;
                16'h3301: path_rom = 8'd143;
                16'h3302: path_rom = 8'd144;
                16'h3303: path_rom = 8'd145;
                16'h3304: path_rom = 8'd146;
                16'h3305: path_rom = 8'd147;
                16'h3306: path_rom = 8'd148;
                16'h3307: path_rom = 8'd64;
                16'h3308: path_rom = 8'd63;
                16'h3309: path_rom = 8'd62;
                16'h330A: path_rom = 8'd46;
                16'h330B: path_rom = 8'd47;
                16'h330C: path_rom = 8'd48;
                16'h330D: path_rom = 8'd49;
                16'h330E: path_rom = 8'd50;
                16'h330F: path_rom = 8'd131;
                16'h3310: path_rom = 8'd130;
                16'h3311: path_rom = 8'd129;
                16'h3312: path_rom = 8'd128;
                16'h3313: path_rom = 8'd127;
                16'h3314: path_rom = 8'd126;
                16'h3315: path_rom = 8'd22;
                16'h3316: path_rom = 8'd23;
                16'h3317: path_rom = 8'd24;
                16'h3318: path_rom = 8'd25;
                16'h3400: path_rom = 8'd142;
                16'h3401: path_rom = 8'd143;
                16'h3402: path_rom = 8'd144;
                16'h3403: path_rom = 8'd145;
                16'h3404: path_rom = 8'd146;
                16'h3405: path_rom = 8'd147;
                16'h3406: path_rom = 8'd148;
                16'h3407: path_rom = 8'd64;
                16'h3408: path_rom = 8'd63;
                16'h3409: path_rom = 8'd62;
                16'h340A: path_rom = 8'd46;
                16'h340B: path_rom = 8'd47;
                16'h340C: path_rom = 8'd48;
                16'h340D: path_rom = 8'd49;
                16'h340E: path_rom = 8'd50;
                16'h340F: path_rom = 8'd131;
                16'h3410: path_rom = 8'd130;
                16'h3411: path_rom = 8'd129;
                16'h3412: path_rom = 8'd128;
                16'h3413: path_rom = 8'd127;
                16'h3414: path_rom = 8'd126;
                16'h3415: path_rom = 8'd125;
                16'h3416: path_rom = 8'd31;
                16'h3417: path_rom = 8'd30;
                16'h3418: path_rom = 8'd29;
                16'h3419: path_rom = 8'd124;
                16'h341A: path_rom = 8'd123;
                16'h341B: path_rom = 8'd122;
                16'h341C: path_rom = 8'd114;
                default: path_rom = 8'd0;
            endcase
        end
    endfunction

    function [3:0] demand_rom;
        input [4:0] addr;
        input [3:0] stop;
        reg [59:0] row;
        begin
            case (addr)
                5'd 0: row = 60'h645588655844888; // Sunny Early Morning
                5'd 1: row = 60'h757698767866988; // Sunny AM Peak
                5'd 2: row = 60'h786648756855888; // Sunny Mid Morning
                5'd 3: row = 60'h786548656855888; // Sunny Lunch
                5'd 4: row = 60'h787648767865888; // Sunny Afternoon
                5'd 5: row = 60'h747688767866888; // Sunny PM Peak
                5'd 6: row = 60'h787648767865888; // Sunny Evening
                5'd 7: row = 60'h645500655044800; // Sunny Night
                5'd 8: row = 60'h686548655854888; // Rain Early Morning
                5'd 9: row = 60'h797659767866989; // Rain AM Peak
                5'd10: row = 60'h747688766855888; // Rain Mid Morning
                5'd11: row = 60'h746588756855888; // Rain Lunch
                5'd12: row = 60'h747688767866888; // Rain Afternoon
                5'd13: row = 60'h747688767866888; // Rain PM Peak
                5'd14: row = 60'h787648767866888; // Rain Evening
                5'd15: row = 60'h646588656054808; // Rain Night
                5'd16: row = 60'h685540645844808; // Festival Early Morning
                5'd17: row = 60'h787588756855444; // Festival AM Peak
                5'd18: row = 60'h746588756855888; // Festival Mid Morning
                5'd19: row = 60'h747588656855800; // Festival Lunch
                5'd20: row = 60'h747688757855888; // Festival Afternoon
                5'd21: row = 60'h747688757855808; // Festival PM Peak
                5'd22: row = 60'h787648756055808; // Festival Evening
                5'd23: row = 60'h706540656054800; // Festival Night
                5'd24: row = 60'h645588555844888; // Storm Early Morning
                5'd25: row = 60'h797658767866988; // Storm AM Peak
                5'd26: row = 60'h686548656855888; // Storm Mid Morning
                5'd27: row = 60'h646588656855888; // Storm Lunch
                5'd28: row = 60'h747688766855888; // Storm Afternoon
                5'd29: row = 60'h787648766855888; // Storm PM Peak
                5'd30: row = 60'h746688766855888; // Storm Evening
                5'd31: row = 60'h545400544044400; // Storm Night
                default: row = 60'h0;
            endcase
            case (stop)
                4'd 0: demand_rom = row[59:56];
                4'd 1: demand_rom = row[55:52];
                4'd 2: demand_rom = row[51:48];
                4'd 3: demand_rom = row[47:44];
                4'd 4: demand_rom = row[43:40];
                4'd 5: demand_rom = row[39:36];
                4'd 6: demand_rom = row[35:32];
                4'd 7: demand_rom = row[31:28];
                4'd 8: demand_rom = row[27:24];
                4'd 9: demand_rom = row[23:20];
                4'd10: demand_rom = row[19:16];
                4'd11: demand_rom = row[15:12];
                4'd12: demand_rom = row[11:8];
                4'd13: demand_rom = row[7:4];
                4'd14: demand_rom = row[3:0];
                default: demand_rom = 4'h0;
            endcase
        end
    endfunction

    function [23:0] stop_color;
        input [3:0] rv;
        reg [7:0] bri;
        begin
            case (rv[1:0]) 2'd3: bri=8'hFF; 2'd2: bri=8'hB0; 2'd1: bri=8'h70; default: bri=8'h30; endcase
            case (rv[3:2]) 2'd1: stop_color={8'h00,8'h00,bri}; 2'd2: stop_color={bri,8'h00,8'h00}; default: stop_color=24'h050505; endcase
        end
    endfunction

    localparam WS_RESET=2'd0, WS_SENDBIT=2'd1, WS_DONE=2'd2;
    reg [1:0]  ws_state;
    reg [15:0] ws_tick;
    reg [7:0]  ws_led;
    reg [4:0]  ws_bit;
    reg        ws_phase, ws_out, frame_done;

    reg        b0_state;      // 0=DWELL 1=TRAVEL
    reg [3:0]  b0_stop_idx;
    reg [7:0]  b0_path_id;
    reg [7:0]  b0_path_step;
    reg [7:0]  b0_path_len;
    reg [9:0]  b0_dwell_tmr;
    reg [5:0]  b0_move_tmr;
    reg        b1_state;      // 0=DWELL 1=TRAVEL
    reg [3:0]  b1_stop_idx;
    reg [7:0]  b1_path_id;
    reg [7:0]  b1_path_step;
    reg [7:0]  b1_path_len;
    reg [9:0]  b1_dwell_tmr;
    reg [5:0]  b1_move_tmr;
    reg        b2_state;      // 0=DWELL 1=TRAVEL
    reg [3:0]  b2_stop_idx;
    reg [7:0]  b2_path_id;
    reg [7:0]  b2_path_step;
    reg [7:0]  b2_path_len;
    reg [9:0]  b2_dwell_tmr;
    reg [5:0]  b2_move_tmr;

    wire [3:0]  b0_rlen     = route_len(rom_addr, 1'b0);
    wire [3:0]  b0_nxt_idx  = (b0_stop_idx + 4'd1 >= b0_rlen) ? 4'd0 : b0_stop_idx + 4'd1;
    wire [7:0]  b0_cur_sled = route_stop_led(rom_addr, 1'b0, b0_stop_idx);
    wire [7:0]  b0_nxt_sled = route_stop_led(rom_addr, 1'b0, b0_nxt_idx);
    wire [7:0]  b0_jrn_pid  = get_path_id(b0_cur_sled, b0_nxt_sled);
    wire [7:0]  b0_jrn_len  = get_path_len(b0_jrn_pid);
    wire [7:0]  b0_disp_led = (b0_state == 1'b0) ? b0_cur_sled : path_rom(b0_path_id, b0_path_step);

    wire [3:0]  b1_rlen     = route_len(rom_addr, 1'b1);
    wire [3:0]  b1_nxt_idx  = (b1_stop_idx + 4'd1 >= b1_rlen) ? 4'd0 : b1_stop_idx + 4'd1;
    wire [7:0]  b1_cur_sled = route_stop_led(rom_addr, 1'b1, b1_stop_idx);
    wire [7:0]  b1_nxt_sled = route_stop_led(rom_addr, 1'b1, b1_nxt_idx);
    wire [7:0]  b1_jrn_pid  = get_path_id(b1_cur_sled, b1_nxt_sled);
    wire [7:0]  b1_jrn_len  = get_path_len(b1_jrn_pid);
    wire [7:0]  b1_disp_led = (b1_state == 1'b0) ? b1_cur_sled : path_rom(b1_path_id, b1_path_step);

    wire [3:0]  b2_nxt_idx  = (b2_stop_idx == 4'd14) ? 4'd0 : b2_stop_idx + 4'd1;
    wire [7:0]  b2_cur_sled = b2_stop_led(b2_stop_idx);
    wire [7:0]  b2_nxt_sled = b2_stop_led(b2_nxt_idx);
    wire [7:0]  b2_jrn_pid  = get_path_id(b2_cur_sled, b2_nxt_sled);
    wire [7:0]  b2_jrn_len  = get_path_len(b2_jrn_pid);
    wire [7:0]  b2_disp_led = (b2_state == 1'b0) ? b2_cur_sled : path_rom(b2_path_id, b2_path_step);

    reg [23:0] cur_color;
    always @(*) begin
        if      (ws_led == 8'd0)        cur_color = 24'h101010; // heartbeat LED0
        else if (ws_led == b0_disp_led) cur_color = 24'hFFFFFF; // bus0 white
        else if (ws_led == b1_disp_led) cur_color = 24'hFFFF00; // bus1 yellow
        else if (ws_led == b2_disp_led) cur_color = 24'h00FFFF; // bus2 cyan
        else if (ws_led == 8'd106) cur_color = stop_color(demand_rom(rom_addr, 4'd0));
        else if (ws_led == 8'd114) cur_color = stop_color(demand_rom(rom_addr, 4'd1));
        else if (ws_led == 8'd33) cur_color = stop_color(demand_rom(rom_addr, 4'd2));
        else if (ws_led == 8'd70) cur_color = stop_color(demand_rom(rom_addr, 4'd3));
        else if (ws_led == 8'd78) cur_color = stop_color(demand_rom(rom_addr, 4'd4));
        else if (ws_led == 8'd25) cur_color = stop_color(demand_rom(rom_addr, 4'd5));
        else if (ws_led == 8'd65) cur_color = stop_color(demand_rom(rom_addr, 4'd6));
        else if (ws_led == 8'd58) cur_color = stop_color(demand_rom(rom_addr, 4'd7));
        else if (ws_led == 8'd95) cur_color = stop_color(demand_rom(rom_addr, 4'd8));
        else if (ws_led == 8'd21) cur_color = stop_color(demand_rom(rom_addr, 4'd9));
        else if (ws_led == 8'd50) cur_color = stop_color(demand_rom(rom_addr, 4'd10));
        else if (ws_led == 8'd44) cur_color = stop_color(demand_rom(rom_addr, 4'd11));
        else if (ws_led == 8'd142) cur_color = stop_color(demand_rom(rom_addr, 4'd12));
        else if (ws_led == 8'd11) cur_color = stop_color(demand_rom(rom_addr, 4'd13));
        else if (ws_led == 8'd1) cur_color = stop_color(demand_rom(rom_addr, 4'd14));
        else                             cur_color = 24'h000000;
    end

    wire cur_bit = cur_color[23 - ws_bit];

    always @(posedge CLOCK_50 or negedge rst_n) begin
        if (!rst_n) begin
            ws_state<=WS_RESET; ws_tick<=0; ws_led<=0; ws_bit<=0; ws_phase<=0; ws_out<=0; frame_done<=0;
        end else begin
            frame_done <= 0;
            case (ws_state)
                WS_RESET: begin
                    ws_out <= 0;
                    if (ws_tick==TRESET-1) begin ws_tick<=0; ws_led<=0; ws_bit<=0; ws_phase<=0; ws_state<=WS_SENDBIT; end
                    else ws_tick <= ws_tick + 1;
                end
                WS_SENDBIT: begin
                    if (!ws_phase) begin
                        ws_out <= 1;
                        if ((cur_bit&&ws_tick==T1H-1)||(!cur_bit&&ws_tick==T0H-1)) begin ws_tick<=0; ws_phase<=1; end
                        else ws_tick <= ws_tick + 1;
                    end else begin
                        ws_out <= 0;
                        if ((cur_bit&&ws_tick==T1L-1)||(!cur_bit&&ws_tick==T0L-1)) begin
                            ws_tick<=0; ws_phase<=0;
                            if (ws_bit==23) begin ws_bit<=0; if (ws_led==NUM_LEDS-1) ws_state<=WS_DONE; else ws_led<=ws_led+1; end
                            else ws_bit <= ws_bit + 1;
                        end else ws_tick <= ws_tick + 1;
                    end
                end
                WS_DONE: begin ws_out<=0; frame_done<=1; ws_state<=WS_RESET; ws_tick<=0; end
            endcase`
        end
    end
    assign GPIO_0_0 = ws_out;

    // ---- Bus 0 state machine (ML-driven) ----
    always @(posedge CLOCK_50 or negedge rst_n) begin
        if (!rst_n) begin
            b0_state     <= 1'b0;
            b0_stop_idx  <= 4'd0;
            b0_path_id   <= 8'd0;
            b0_path_step <= 8'd0;
            b0_path_len  <= 8'd1;
            b0_dwell_tmr <= 10'd400;
            b0_move_tmr  <= 6'd20;
        end else if (frame_done) begin
            if (sw_changed) begin
                b0_state     <= 1'b0;
                b0_stop_idx  <= 4'd0;
                b0_path_id   <= 8'd0;
                b0_path_step <= 8'd0;
                b0_path_len  <= 8'd1;
                b0_dwell_tmr <= 10'd400;
                b0_move_tmr  <= 6'd20;
            end else if (b0_state == 1'b0) begin // DWELL
                if (b0_dwell_tmr == 10'd0) begin
                    if (b0_rlen > 4'd1 && b0_jrn_len > 8'd1) begin
                        b0_state     <= 1'b1;
                        b0_path_id   <= b0_jrn_pid;
                        b0_path_len  <= b0_jrn_len;
                        b0_path_step <= 8'd1;
                        b0_stop_idx  <= b0_nxt_idx;
                        b0_move_tmr  <= 6'd20;
                    end else begin
                        b0_dwell_tmr <= 10'd400;
                    end
                end else b0_dwell_tmr <= b0_dwell_tmr - 10'd1;
            end else begin // TRAVEL
                if (b0_move_tmr == 6'd0) begin
                    if (b0_path_step >= b0_path_len - 8'd1) begin
                        b0_state     <= 1'b0;
                        b0_dwell_tmr <= 10'd400;
                    end else begin
                        b0_path_step <= b0_path_step + 8'd1;
                        b0_move_tmr  <= 6'd20;
                    end
                end else b0_move_tmr <= b0_move_tmr - 6'd1;
            end
        end
    end

    // ---- Bus 1 state machine (ML-driven) ----
    always @(posedge CLOCK_50 or negedge rst_n) begin
        if (!rst_n) begin
            b1_state     <= 1'b0;
            b1_stop_idx  <= 4'd0;
            b1_path_id   <= 8'd0;
            b1_path_step <= 8'd0;
            b1_path_len  <= 8'd1;
            b1_dwell_tmr <= 10'd400;
            b1_move_tmr  <= 6'd20;
        end else if (frame_done) begin
            if (sw_changed) begin
                b1_state     <= 1'b0;
                b1_stop_idx  <= 4'd0;
                b1_path_id   <= 8'd0;
                b1_path_step <= 8'd0;
                b1_path_len  <= 8'd1;
                b1_dwell_tmr <= 10'd400;
                b1_move_tmr  <= 6'd20;
            end else if (b1_state == 1'b0) begin // DWELL
                if (b1_dwell_tmr == 10'd0) begin
                    if (b1_rlen > 4'd1 && b1_jrn_len > 8'd1) begin
                        b1_state     <= 1'b1;
                        b1_path_id   <= b1_jrn_pid;
                        b1_path_len  <= b1_jrn_len;
                        b1_path_step <= 8'd1;
                        b1_stop_idx  <= b1_nxt_idx;
                        b1_move_tmr  <= 6'd20;
                    end else begin
                        b1_dwell_tmr <= 10'd400;
                    end
                end else b1_dwell_tmr <= b1_dwell_tmr - 10'd1;
            end else begin // TRAVEL
                if (b1_move_tmr == 6'd0) begin
                    if (b1_path_step >= b1_path_len - 8'd1) begin
                        b1_state     <= 1'b0;
                        b1_dwell_tmr <= 10'd400;
                    end else begin
                        b1_path_step <= b1_path_step + 8'd1;
                        b1_move_tmr  <= 6'd20;
                    end
                end else b1_move_tmr <= b1_move_tmr - 6'd1;
            end
        end
    end

    // ---- Bus 2 state machine (fixed all-stops circuit, cyan) ----
    // Bus 2 is independent of ML data - does NOT reset on sw_changed.
    // Starts at stop 7 (S08) to spread visually from buses 0 and 1.
    always @(posedge CLOCK_50 or negedge rst_n) begin
        if (!rst_n) begin
            b2_state     <= 1'b0;
            b2_stop_idx  <= 4'd7;   // S08 start (spread from buses 0+1)
            b2_path_id   <= 8'd0;
            b2_path_step <= 8'd0;
            b2_path_len  <= 8'd1;
            b2_dwell_tmr <= 10'd400;
            b2_move_tmr  <= 6'd20;
        end else if (frame_done) begin
            if (b2_state == 1'b0) begin // DWELL
                if (b2_dwell_tmr == 10'd0) begin
                    if (b2_jrn_len > 8'd1) begin
                        b2_state     <= 1'b1;
                        b2_path_id   <= b2_jrn_pid;
                        b2_path_len  <= b2_jrn_len;
                        b2_path_step <= 8'd1;
                        b2_stop_idx  <= b2_nxt_idx;
                        b2_move_tmr  <= 6'd20;
                    end else begin
                        b2_dwell_tmr <= 10'd400;
                    end
                end else b2_dwell_tmr <= b2_dwell_tmr - 10'd1;
            end else begin // TRAVEL
                if (b2_move_tmr == 6'd0) begin
                    if (b2_path_step >= b2_path_len - 8'd1) begin
                        b2_state     <= 1'b0;
                        b2_dwell_tmr <= 10'd400;
                    end else begin
                        b2_path_step <= b2_path_step + 8'd1;
                        b2_move_tmr  <= 6'd20;
                    end
                end else b2_move_tmr <= b2_move_tmr - 6'd1;
            end
        end
    end

    assign LEDR[1:0] = SW[1:0];      // current scenario
    assign LEDR[2]   = b0_state;     // 1=bus0 travelling
    assign LEDR[3]   = b1_state;     // 1=bus1 travelling
    assign LEDR[4]   = b2_state;     // 1=bus2 travelling
    assign LEDR[5]   = SW[9];        // 1=demo mode active
    assign LEDR[6]   = 1'b0;
    assign LEDR[7]   = ~b0_state;    // 1=bus0 at stop
    assign LEDR[8]   = ~b1_state;    // 1=bus1 at stop
    assign LEDR[9]   = rst_n;        // 1=system running

endmodule
